# version of docker-compose
version: '3.9'
# 'services' are equivalent to 'containers'
services:
  test-redis:
    # Use Docker Hub base image 'redis:alpine' 
    image: 'redis:alpine'
  test-webapp:
    restart: on-failure
    build: ./test-webapp
    # Specify an array of ports to map
    ports:
      - '80:5000'
